listening-port=3478
tls-listening-port=5349

listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=185.244.172.90

fingerprint
lt-cred-mech

realm=rlink.local
user=rlink:s7yd9vLTNjhyWJr1TLfBUqhj

no-multicast-peers
stale-nonce=600
no-cli
no-loopback-peers

min-port=49160
max-port=49200

log-file=stdout
simple-log
